### PR TITLE
Add add_vertex!, add_vertices!, add_edge! methods 

### PR DESCRIPTION
**Pull request by dpsanders**
- Change `AbstractVector` -> `Vector` in the type definition.
- Add convenience constructors for `Network` with given types (including allowing `Void` for edges to label only vertices).
- Add `add_vertex!`, `add_vertices!`, `add_edge!` methods.

### CODE REVIEW

**Comment by CarloLucibello** [comment]
can you rebase? (updated travis and require)

**Comment by dpsanders** [comment]
OK, rebased.

**Comment by CarloLucibello** [comment]
looks like you have to change the tests according to the new syntax

**Comment by dpsanders** [comment]
Now passing tests, including some basic tests of the new functionality for `add_vertex!`.

**Comment by CarloLucibello** [comment]
ok, thanks! This package is very open to any new design direction, also radical ones, very little thought has gone into that at the moment. Feell free to share any ideas you have, bye

**Pull request merged**
